
  
server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials

#<<< API Gateway / Routes
      routes:
        - id: payment
          uri: http://localhost:8082
          predicates:
            - Path=/payments/**
          filters:
            - AuthorizationFilter
             
        - id: flightReservation
          uri: http://localhost:8083
          predicates:
            - Path=/flightReservations/**
          filters:
            - AuthorizationFilter

        - id: user
          uri: http://localhost:8084
          predicates:
            - Path=/users/**,
          # filters:
          #   - AuthorizationFilter
            
        - id: myPage
          uri: http://localhost:8085
          predicates:
            - Path=
          filters:
            - AuthorizationFilter

        - id: screen
          uri: http://localhost:8086
          predicates:
            - Path=/flights/**
          filters:
            - AuthorizationFilter
            
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
#>>> API Gateway / Routes
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            exposedHeaders:
              - "Authorization"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials

      routes:
        - id: payment
          uri: http://payment:8080
          predicates:
            - Path=/payments/**
          filters:
            - AuthorizationFilter

        - id: flightReservation
          uri: http://flightReservation:8080
          predicates:
            - Path=/flightReservations/**
          filters:
            - AuthorizationFilter

        - id: user
          uri: http://user:8080
          predicates:
            - Path=/users/**, 
        - id: myPage
          uri: http://myPage:8080
          predicates:
            - Path=
          filters:
            - AuthorizationFilter

        - id: screen
          uri: http://screen:8080
          predicates:
            - Path=/flights/**, 

        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            exposedHeaders:
              - "Authorization"

            allowCredentials: true

server:
  port: 8080
