api:
  serviceKey: "6EFB7dfc%2B%2F3KMt90OiG%2FDgWOPzG9bQh45E%2FXXfq0XZS%2FBZAe7D0o4eBQOga%2FMof9BTZDQ3li%2BnatPbWc4MG0Ug%3D%3D"
  mobileOS: "ETC"
  mobileApp: "AppTest"
  arrange: "A"

server:
  port: 8080

spring:
  application:
    name: lodging
---

spring:
  profiles: default
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        implicit_naming_strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: lodging
#<<< EDA / Topic Name
          destination: travel
#>>> EDA / Topic Name
          contentType: application/json
        event-out:
#<<< EDA / Topic Name
          destination: travel
#>>> EDA / Topic Name
          contentType: application/json

logging:
  level:
    org.hibernate.type: info
    org.springframework.cloud: info


server:
  port: 8087

---

spring:
  profiles: docker
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        implicit_naming_strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
  cloud:
    stream:
      kafka:
        binder:
          brokers: my-kafka:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: lodging
          destination: travel
          contentType: application/json
        event-out:
          destination: travel
          contentType: application/json


