server:
  port: 8080

spring:
  application:
    name: lodgingreservation
---

spring:
  profiles: default
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        implicit_naming_strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: lodgingReservation
#<<< EDA / Topic Name
          destination: travel
#>>> EDA / Topic Name
          contentType: application/json
        event-out:
#<<< EDA / Topic Name
          destination: travel
#>>> EDA / Topic Name
          contentType: application/json

logging:
  level:
    org.hibernate.type: info
    org.springframework.cloud: info

api:
  url: 
    lodgingReservation: localhost:8088
    lodging: localhost:8087

server:
  port: 8088

---

spring:
  profiles: docker
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        implicit_naming_strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
  cloud:
    stream:
      kafka:
        binder:
          brokers: my-kafka:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: lodgingReservation
          destination: travel
          contentType: application/json
        event-out:
          destination: travel
          contentType: application/json


api:
  url: 
    lodgingReservation: lodgingReservation:8088
    lodging: lodging:8087